services:

  portainer:

    image: portainer/portainer-ce:lts

    container_name: portainer

    restart: unless-stopped

    ports:

      - "8000:8000"

      - "9443:9443"

    volumes:

      - /var/run/docker.sock:/var/run/docker.sock

      - /opt/bdip/data/portainer:/data

    networks:

      - bdip-net

networks:

  bdip-net:

    external: true
